POST https://nodepostgres-production.up.railway.app/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o video 01",
  "duration": 360
}

###

GET https://nodepostgres-production.up.railway.app/videos

###

PUT https://nodepostgres-production.up.railway.app/videos/
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o video 01",
  "duration": 360
}

###

DELETE https://nodepostgres-production.up.railway.app/videos/
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o video 01",
  "duration": 360
}