POST https://nodepostgres-production.up.railway.app/
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o video 01",
  "duration": 360
}

###

GET https://nodepostgres-production.up.railway.app/

###

PUT https://nodepostgres-production.up.railway.app/9bb7e2a5-dfd0-4fc1-ab8b-4d57693c408e
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o video 01",
  "duration": 360
}

###

DELETE https://nodepostgres-production.up.railway.app/0a5dd4bf-9398-4d1e-8dc4-e7a04d3cba87
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o video 01",
  "duration": 360
}